/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package panel;

import Model.SanPham;
import Service.poloService;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author khoad
 */
public class ExcelPreview extends javax.swing.JFrame {

    /** Creates new form ExcelPreview */
    public ExcelPreview() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    
    poloService PLS = new poloService();
    SanPhamView view = new SanPhamView();
    
    public void loadDataSP(ArrayList<SanPham> splist) {
        DefaultTableModel dtm = (DefaultTableModel) tblPreview.getModel();
        dtm.setRowCount(0);
        for (SanPham sp : splist) {
            dtm.addRow(new Object[]{
                sp.getTenSP(),
                sp.getMoTa(),
                sp.getDanhMuc(),
                sp.getMauSac(),
                sp.getKichCo(),
                sp.getChatLieu(),
                sp.getSoLuong(),
                sp.getDonGia()
            });
        }
    }

    public ArrayList<SanPham> getSPList() {
        ArrayList<SanPham> splist = new ArrayList<>();
        for (int i = 0; i < tblPreview.getRowCount(); i++) {
            SanPham sp = new SanPham();
            sp.setTenSP((String) tblPreview.getValueAt(i, 0));
            sp.setMoTa((String) tblPreview.getValueAt(i, 1));
            sp.setMaDM(PLS.getDMid((String) tblPreview.getValueAt(i, 2)).getId());
            sp.setMaMS(PLS.getMSid((String) tblPreview.getValueAt(i, 3)).getId());
            sp.setMaKC(PLS.getKCid((String) tblPreview.getValueAt(i, 4)).getId());
            sp.setMaCL(PLS.getCLid((String) tblPreview.getValueAt(i, 5)).getId());
            sp.setSoLuong(Integer.valueOf(tblPreview.getValueAt(i, 6).toString()));
            sp.setDonGia(Integer.valueOf(tblPreview.getValueAt(i, 7).toString()));
            splist.add(sp);
        }
        return splist;
    }
    
    public void insertSP(ArrayList<SanPham> splist) {
        for (SanPham sp : splist) {
            PLS.addSP(sp);
        }
        JOptionPane.showMessageDialog(this, "Nhập file thành công");
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPreview = new javax.swing.JTable();
        btnNhapEX = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Xem trước File");

        tblPreview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Tên SP", "Mô Tả", "Danh Mục", "Màu Sắc", "Kích Cỡ", "Chất Liệu", "Số Lượng", "Đơn Giá"
            }
        ));
        jScrollPane1.setViewportView(tblPreview);

        btnNhapEX.setText("Nhập");
        btnNhapEX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapEXActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNhapEX)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNhapEX)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNhapEXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapEXActionPerformed
        insertSP(getSPList());
        view.loadDataSP(PLS.getListSP());
        this.dispose();
    }//GEN-LAST:event_btnNhapEXActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExcelPreview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExcelPreview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExcelPreview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExcelPreview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExcelPreview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNhapEX;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPreview;
    // End of variables declaration//GEN-END:variables

}
